### PR TITLE
Bug 1291340 - Convert & store sync data to Parquet

### PR DESCRIPTION
**Pull request by mreid-moz**
This change is [Reviewable](https://reviewable.io/reviews/mozilla-services/data-pipeline/231)

### CODE REVIEW

**Comment by mreid-moz** [comment]
I have tested this notebook by running on an adhoc cluster, some sample data is available on S3 at
- `s3://net-mozaws-prod-us-west-2-pipeline-analysis/mreid/sync_log/v1/`
- `s3://net-mozaws-prod-us-west-2-pipeline-analysis/mreid/sync_log_device_activity/v1/`
- `s3://net-mozaws-prod-us-west-2-pipeline-analysis/mreid/sync_log_device_counts/v1/`

**Comment by vitillo** [comment]
The Dataset hack isn't very future proof. Maybe adding that functionality directly to moztelemetry would make more sense? There are no tests as well and I can't help but feel that a notebook is not the right format to package this job, more so if this is going to have to run for a long while and we are planning to make changes to it.

**Comment by mreid-moz** [comment]
Agreed re: the Dataset hack. Per previous discussion with @maurodoglio, I plan to send a separate PR to moztelemetry to make "summaries" generally available for filtering / manipulation, and add the ability to load records from a given set of summaries. It might still make sense to be able to use a lambda for the case when there's a very large number of summaries.

I can probably also make a change to the "standard" heka decoder to handle a missing message Payload, which would further reduce the untested code.

A notebook seemed the most approachable form for this kind of code - I'm not sure how long-lived it will be, nor who might want to make changes to it. I suspect that the pipeline's new "direct to parquet" output functionality will obsolete almost all of the non-SQL parts of this code in the next quarter or two.

**Comment by mreid-moz** [comment]
> I can probably also make a change to the "standard" heka decoder to handle a missing message Payload, which would further reduce the untested code.

I took another look at this and the problem is not with the message `payload`, but rather with the assumption that field names containing a `.` contain json strings and represent nested structures inside the logical json doc. I'm not sure that's something we want to change in the normal decoder.

**Comment by maurodoglio** [comment]
@mreid-moz heads up: I implemented the [changes to moztelemetry](https://github.com/mozilla/python_moztelemetry/pull/91) we talked about.

**Comment by mreid-moz** [comment]
Thanks @maurodoglio !

**Comment by mreid-moz** [comment]
@vitillo I filed [bug 1318762](https://bugzilla.mozilla.org/show_bug.cgi?id=1318762) to address the "overly complex notebook" issue. That will let us run python-based jobs that are more complex, but which we don't necessarily want/need to port to Scala, while still allowing for test coverage and code reuse.

Sound OK?

**Comment by vitillo** [comment]
@mreid-moz OK

**Comment by vitillo** [comment]
@mreid-moz, can we move this notebook to RTMO?

**Comment by mreid-moz** [comment]
Yep, I'll do that next week.

**Comment by mreid-moz** [comment]
Closing in favour of https://github.com/mozilla/mozilla-reports/pull/7

That PR addresses the "dataset hack" problem and moves the notebook to a better home.

**Pull request closed without merging**
