### PR TITLE
Migrate the telemetry code to a luasandbox moz_telemetry package

### PR DESCRIPTION
**Pull request by trink**
https://github.com/mozilla-services/lua_sandbox_extensions/pull/3

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla-services/data-pipeline/220)

### CODE REVIEW

**Comment by mreid-moz** [comment]
Please update the README with a description and link of where to find the lua_sandbox_extensions.

**Comment by mreid-moz** [comment]
Looks like the `bin/build_pipeline_heka.sh` script needs an update to where it looks for hindsight modules too.

**Comment by trink** [comment]
removing from the .sh (they only get build and packaged in 1 place now)

**Comment by mreid-moz** [comment]
I think the README should still point at the new home for sandbox extensions so old docs/links can still be followed to the current code.

**Pull request closed without merging**
