### PR TITLE
Bug 1316336 - Make the churn notebook report public

### PR DESCRIPTION
**Pull request by acmiyaguchi**
As per [bug 1316336](https://bugzilla.mozilla.org/show_bug.cgi?id=1316336), this adds the churn notebook so it is available to the data platform. This allows us to schedule the churn notebook through Airflow.

r? @Dexterp37

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla-services/data-pipeline/234)

### CODE REVIEW

**Comment by vitillo** [comment]
Can we move this notebook to [RTMO](https://mail.mozilla.org/pipermail/fhr-dev/2016-November/001088.html)?

**Comment by Dexterp37** [comment]
Would this require any non trivial change (other than adding the metadata and moving the file)? It seems like a good idea to me anyway. @mreid-moz, any opinion on that?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/234#-:-KXou4Nh4rncLh0TxrlZ:b-rqeyi6)*

**Comment by vitillo** [comment]
No non trivial changes are required afaik.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/234#-:-KXp_4hwV2kXbAJ32k2Y:b-y1mrwc)*

**Comment by mreid-moz** [comment]
I think this job is a good candidate to be handled as described in [Bug 1318762](https://bugzilla.mozilla.org/show_bug.cgi?id=1318762), but given that infra is not yet available, I'm OK with this notebook going either into RTMO or into this repo as-is.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/234#-:-KXpzmH6zazsSRDP1Pfa:by5vajt)*

**Comment by Dexterp37** [comment]
Nice, let's use this as a nice first real-world example on RTMO then :-D @acmiyaguchi, would you mind moving this notebook to RTMO as pointed out by Roberto? 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/234#-:-KXq1Aws_mwpY6xQoECh:bhcor0k)*

**Comment by acmiyaguchi** [comment]
I think it is more appropriate for the notebook to be maintained here and later submitted to `mozilla-reports` based on my experience in porting a notebook to a knowledge post and working with the `knowledge_repo` tool.

Updating a notebook living directly in `mozilla-reports` will be tricky. The knowledge repository makes the assumption that reports live outside of the repository and will be converted to a post indexed in the repository. It can keep a copy of the original source, but it's probably not the best way to keep track of a notebook like this one. 

This notebook is probably best viewed as a batch view job, which may not be the best candidate for a knowledge post. Ideally, this notebook would be converted into a more robust python (or scala) job backed by tests as described in the bug mentioned by @mreid-moz .

**Comment by vitillo** [comment]
The knowledge repo keeps a copy of the notebook and we could schedule that copy from Airflow. I agree this isn't really an analysis but an ETL job which shouldn't have been written in a Jupyter notebook. That said, the notebook is still useful for others to learn how to query data and what not, so in that sense it would be nice to have this indexed.

**Comment by acmiyaguchi** [comment]
I like the idea of having this churn notebook and its revisions visible in this repository's history. I think adding it to the knowledge repository is also a good idea, but I don't necessarily want to make it the primary source of the notebook.

**Comment by Dexterp37** [comment]
@acmiyaguchi could you please rebase the Churn file toward the latest python notebook version?

**Comment by Dexterp37** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/234#-:-KYa6CQiAgPbJRCbjp6u:bnfp4nl)*

**Comment by Dexterp37** [comment]
@vitillo, I can't merge that due to.. permissions. Would you mind doing it?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/234#-:-KYyRN52W_z4nlnZP0Yt:b-ercg6b)*

**Pull request merged**
