### PR TITLE
Bug 1314120 - Socorro Import - Add schema generation and versioning in s3 path

### PR DESCRIPTION
**Pull request by acmiyaguchi**
These patches are related to productionizing Socorro crash data into the data platform as outlined in [bug 1314120](https://bugzilla.mozilla.org/show_bug.cgi?id=1314120). This patch does the following:

- downloads crash report schema from Socorro github repository as a fallback, with the primary location published alongside the data TBA
- replaces hardcoded Spark schema with one that is generated from a JSON schema
- s3 path now includes version number of schema
- uses logging instead of print

@mreid-moz r?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla-services/data-pipeline/229)

### CODE REVIEW

**Comment by mreid-moz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 71 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVjhZeBRPcB65LWMHz-:-KVjhZeBRPcB65LWMHz0:b-g5094j) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L71)):_

> ```
>     "    elif '$ref' in str(schema):\n",
>     "        log.error(\"Reference not found for schema: {}\".format(str(schema)))\n",
>     "        raise Exception\n",
> ```

Let's store the error message in a variable, then we can log it and then `raise ValueError(err_msg)`. This should give us more helpful debugging info if there is an error.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 78 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVjhciyBuTjOpwvz9o5:-KVjhciyBuTjOpwvz9o6:b-9n6sfc) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L78)):_

> ```
>     "    if 'properties' not in schema:\n",
>     "        log.error(\"Invalid JSON schema: properties field is missing.\")\n",
>     "        raise Exception\n",
> ```

Similar: please raise `ValueError` with the descriptive error message here and other cases like this.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 131 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVk1oSnwwdBvhnWQTYS:-KVk1oSnwwdBvhnWQTYT:b-2tbzcu) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L131)):_

> ```
>     "    log.info(\"Fetching latest crash data schema from {}\"\n",
>     "             .format(primary_url))\n",
>     "    resp = urllib2.urlopen(primary_url)\n",
> ```

I think we'll need to use `boto` to fetch this data from the S3 location.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 132 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVk1wEtbkWE6ctT71mp:-KVk1wEtbkWE6ctT71mq:bhgxhau) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L132)):_

> ```
>     "             .format(primary_url))\n",
>     "    resp = urllib2.urlopen(primary_url)\n",
>     "except Exception as e:\n",
> ```

Is there a more specific type of exception you can catch here?

---

_[reports/socorro_import/ImportCrashData.ipynb, line 138 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVk2YwF3FFa7G2Zc2ZB:-KVk2YwGfY9yOzSYa-9x:brw7us9) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L138)):_

> ```
>     "    resp = urllib2.urlopen(fallback_url)\n",
>     "\n",
>     "data = json.load(resp)"
> ```

Please use a more descriptive variable name

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229)_

**Comment by acmiyaguchi** [comment]
I've addressed the issues above with the most recent commit. 

I'm also wondering data with schema's without `$target_version` should default to `/v1`. I currently have it defaulting to `/v0`, but I'm not sure that makes sense.

**Comment by mreid-moz** [comment]
I think v0 makes sense - that ensures that data for a missing version won't interfere or be mixed in with a legitimate version.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 71 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVjhZeBRPcB65LWMHz-:-KVzAGg4LSBgRmxSbl9L:bb6ywmx) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L71)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> Let's store the error message in a variable, then we can log it and then `raise ValueError(err_msg)`. This should give us more helpful debugging info if there is an error.
> </details>
> LGTM

---

_[reports/socorro_import/ImportCrashData.ipynb, line 78 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVjhciyBuTjOpwvz9o5:-KVzALbjoJ4G4TIhOqww:bb6ywmx) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L78)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> Similar: please raise `ValueError` with the descriptive error message here and other cases like this.
> </details>
> LGTM

---

_[reports/socorro_import/ImportCrashData.ipynb, line 131 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVk1oSnwwdBvhnWQTYS:-KVzBOdQmU47-BleMs-f:bb6ywmx) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L131)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> I think we'll need to use `boto` to fetch this data from the S3 location.
> </details>
> LGTM

---

_[reports/socorro_import/ImportCrashData.ipynb, line 132 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVk1wEtbkWE6ctT71mp:-KVzAfCwTW5QyStrtE3P:bb6ywmx) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L132)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> Is there a more specific type of exception you can catch here?
> </details>
> LGTM

---

_[reports/socorro_import/ImportCrashData.ipynb, line 138 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVk2YwF3FFa7G2Zc2ZB:-KVzBZWuZcMoPWiuVkXl:bb6ywmx) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L138)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> Please use a more descriptive variable name
> </details>
> LGTM

---

_[reports/socorro_import/ImportCrashData.ipynb, line 143 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzBBQRTDkGg4GYdXTW:-KVzBBQSSJEX4WDoHDJG:biulnmm) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L143)):_

> ```
>     "\n",
>     "bucket = \"todo-bucket\"\n",
>     "key = \"todo-key\"\n",
> ```

Please add a variable for `region` and set it to `us-west-2`

---

_[reports/socorro_import/ImportCrashData.ipynb, line 148 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzCrAsRQW8qBEqPTiH:-KVzCrAtnKanF-XYrzGj:b-snfvpp) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L148)):_

> ```
>     "try:\n",
>     "    log.info(\"Fetching latest crash data schema from s3://{}/{}\"\n",
>     "             .format(bucket, key))\n",
> ```

Nit: you can put the `.format(...)` bit on the previous line

---

_[reports/socorro_import/ImportCrashData.ipynb, line 149 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzBGR5HKKJomI-KpZY:-KVzBGR6Co7f4fHSHz7N:bt2sw1p) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L149)):_

> ```
>     "    log.info(\"Fetching latest crash data schema from s3://{}/{}\"\n",
>     "             .format(bucket, key))\n",
>     "    s3 = boto3.client('s3')\n",
> ```

Please add the `region` arg after `s3` per above

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-:-KVzBiK-uSHOdNy-0pj2:b-jr6u5q)_

**Comment by mreid-moz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 143 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzBBQRTDkGg4GYdXTW:-KW-DjQVhMtJN0CIT93F:bb6ywmx) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L143)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> Please add a variable for `region` and set it to `us-west-2`
> </details>
> LGTM

---

_[reports/socorro_import/ImportCrashData.ipynb, line 148 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzCrAsRQW8qBEqPTiH:-KW-EfwQPN1btUkmvBsR:bb6ywmx) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L148)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> Nit: you can put the `.format(...)` bit on the previous line
> </details>
> LGTM

---

_[reports/socorro_import/ImportCrashData.ipynb, line 149 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzBGR5HKKJomI-KpZY:-KW-EeJghfDtMUz5ilju:bb6ywmx) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L149)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> Please add the `region` arg after `s3` per above
> </details>
> LGTM

---

_[reports/socorro_import/ImportCrashData.ipynb, line 143 at r3](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KW-GnTTyqTAiGD7VTm4:-KW-GnTTyqTAiGD7VTm5:b99248l) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/1129653b4833e65bc0aad48079bc8b8c50b4a48a/reports/socorro_import/ImportCrashData.ipynb#L143)):_

> ```
>     "\n",
>     "region = \"us-west-2\"\n",
>     "bucket = \"todo-bucket\"\n",
> ```

Please update `bucket` and `key` per recent comments in Bug 1314120.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229)_

**Comment by mreid-moz** [comment]
Once the `bucket` and `key` changes have been made, please try manually running this notebook for "yesterday" using the following buckets:

``` python
source_s3path = "s3://org-mozilla-telemetry-crashes/v1/crash_report"
dest_s3path = "s3://telemetry-test-bucket/socorro_crash/"
```

A cluster size of 10 nodes should make it relatively quick to test.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 196 at r3](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KW-HusT2p5_NtVX5UKu:-KW-HusT2p5_NtVX5UKv:b-z9k4y9) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/1129653b4833e65bc0aad48079bc8b8c50b4a48a/reports/socorro_import/ImportCrashData.ipynb#L196)):_

> source_s3path = \"s3://org-allizom-telemetry-crashes/v1/crash_report\"\n",

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-:-KW-HMgdUE1sKR--NzZS:bhuyt9a)_

**Comment by acmiyaguchi** [comment]
The new commit assumes the location of the `crash_report.json` is at the root of the bucket. The results of the manual backfill can be found `s3://telemetry-test-bucket/socorro_crash/v1/crash_date=20161106/`.

**Comment by mreid-moz** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 143 at r3](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KW-GnTTyqTAiGD7VTm4:-KW407crJA56hBAZ54k8:bb6ywmx) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/1129653b4833e65bc0aad48079bc8b8c50b4a48a/reports/socorro_import/ImportCrashData.ipynb#L143)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> Please update `bucket` and `key` per recent comments in Bug 1314120.
> </details>
> LGTM

---

_[reports/socorro_import/ImportCrashData.ipynb, line 202 at r4](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KW41lsuciB79HoHSSl9:-KW41lsuciB79HoHSSlA:bwuuq6v) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/1eb1e3eb2618eb334316922cf4e35d5db7ac4681/reports/socorro_import/ImportCrashData.ipynb#L202)):_

> ```
>     "    source_s3path = \"s3://org-mozilla-telemetry-crashes/v1/crash_report\"\n",
>     "    dest_s3path = \"s3://telemetry-test-bucket/socorro_crash/\"\n",
>     "    num_partitions = 5\n",
> ```

Based on the test you ran, the resulting parquet files appear to be > 1GB in size.  Assuming for now that this is representative, let's increase `num_partitions` to 10.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229)_

**Comment by mreid-moz** [comment]
One general concern (per IRC conversation) is that airflow runs these scripts with `--allow-errors` set to true, so an exception will **not** currently interrupt the rest of the notebook. That means we may want to structure things such that we explicitly check all necessary preconditions before running the final `import_day` call. At a glance, it looks like the code will fail if the schema cannot be fetched, so it should be safe as-is.

Please take a look and see if you agree. If not, we should add a check that we were able to fetch the schema before importing.

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 201 at r5](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KWEYv99NAzgQCpLRGb0:-KWEYv9A6tZHBV0ASZ-I:b-sz3o4n) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/d62a1c36fabe5287be8207e1d0d06b063db9ea60/reports/socorro_import/ImportCrashData.ipynb#L201)):_

> ```
>     "def import_day(d):\n",
>     "    source_s3path = \"s3://org-mozilla-telemetry-crashes/v1/crash_report\"\n",
>     "    dest_s3path = \"s3://telemetry-test-bucket/socorro_crash/\"\n",
> ```

One (hopefully final) change to the bucket paths: let's switch this over to the `telemetry-parquet` bucket.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-:-KWEdMGyEDZzjyCngopv:bpv38z8)_

**Comment by acmiyaguchi** [comment]
I ran this notebook for 20161109 and it looks like everything is working, in particular the schema at the s3 location. I also put everything at the top level into a single cell to minimize the chance of running into the airflow error handling path.

**Comment by mreid-moz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-:-KWFhgNQu89KorLfMTt0:bnfp4nl)_

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 143 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzBBQRTDkGg4GYdXTW:-KWFicUEXPwFrDvAnvMG:bmxilld) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L143)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> LGTM
> </details>
> :LGTM:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229)_

**Comment by acmiyaguchi** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 71 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVjhZeBRPcB65LWMHz-:-KWFjDWqz_c18RmZANtv:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L71)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> LGTM
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 78 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVjhciyBuTjOpwvz9o5:-KWFjL7yvBVVWipMg0rE:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L78)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> LGTM
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 131 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVk1oSnwwdBvhnWQTYS:-KWFjGc9AmSc3qUFJnyA:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L131)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> LGTM
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 132 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVk1wEtbkWE6ctT71mp:-KWFixWHMqkPGPQl4Z6a:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L132)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> LGTM
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 138 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVk2YwF3FFa7G2Zc2ZB:-KWFixDvPYRsa69z86Au:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/55c10122c4f26b22b69d70510c8f3428bf3a4ebc/reports/socorro_import/ImportCrashData.ipynb#L138)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> LGTM
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 143 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzBBQRTDkGg4GYdXTW:-KWFjFMnBY0SWHPw0LwQ:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L143)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> :LGTM:
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 148 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzCrAsRQW8qBEqPTiH:-KWFjGC69Qv88IY_WwpZ:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L148)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> LGTM
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 149 at r2](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KVzBGR5HKKJomI-KpZY:-KWFjFkm1QY1nn6t971-:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/ecfd498120d4f68fbff1d86b62bc719fe8a333bb/reports/socorro_import/ImportCrashData.ipynb#L149)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> LGTM
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 143 at r3](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KW-GnTTyqTAiGD7VTm4:-KWFjEvTJKHyhjCQ5h5E:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/1129653b4833e65bc0aad48079bc8b8c50b4a48a/reports/socorro_import/ImportCrashData.ipynb#L143)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> LGTM
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 196 at r3](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KW-HusT2p5_NtVX5UKu:-KWFjHkbIU56bP8wr-W2:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/1129653b4833e65bc0aad48079bc8b8c50b4a48a/reports/socorro_import/ImportCrashData.ipynb#L196)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> > source_s3path = \"s3://org-allizom-telemetry-crashes/v1/crash_report\"\n",
> > </details>
> > Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 202 at r4](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KW41lsuciB79HoHSSl9:-KWFiv_fEGtEpfdSLAoa:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/1eb1e3eb2618eb334316922cf4e35d5db7ac4681/reports/socorro_import/ImportCrashData.ipynb#L202)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> Based on the test you ran, the resulting parquet files appear to be > 1GB in size.  Assuming for now that this is representative, let's increase `num_partitions` to 10.
> </details>
> Done.

---

_[reports/socorro_import/ImportCrashData.ipynb, line 201 at r5](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229#-KWEYv99NAzgQCpLRGb0:-KWFiw4jIQxUwE8aU6Xm:b-896fix) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/d62a1c36fabe5287be8207e1d0d06b063db9ea60/reports/socorro_import/ImportCrashData.ipynb#L201)):_
<details><summary>

<i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>



> One (hopefully final) change to the bucket paths: let's switch this over to the `telemetry-parquet` bucket.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/229)_

**Pull request merged**
