### PR TITLE
Bug 1338941 - notebook for new update out of date dashboard

### PR DESCRIPTION
**Pull request by RobertTStrong**
Notebook for the new update out of date dashboard. I'll update the web page, etc. separately.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla-services/data-pipeline/242)

### CODE REVIEW

**Comment by RobertTStrong** [comment]
Perhaps it would be better to add the new notebook and then remove the old notebook sometime in the future?

**Comment by vitillo** [comment]
This notebook should be moved to [RTMO](https://github.com/mozilla/mozilla-reports). Among other things, it's much easier to review notebooks over there as they get converted to Markdown before being committed.

**Comment by chutten** [comment]
Does RTMO schedule, run, and direct the output of results? This is in conjunction with [this pull request](https://github.com/mozilla/telemetry-dashboard/pull/286) which will be querying the results over XHR.

**Comment by chutten** [comment]
(I'm not clear at all on what mozilla-services is about :S )

**Comment by vitillo** [comment]
We originally started to store notebooks in this repo because there wasn't a more appropriate location for them.

Please have a look at the [announcement](https://mail.mozilla.org/pipermail/fhr-dev/2016-November/001088.html) of [RTMO](http://reports.telemetry.mozilla.org/) on fhr-dev. RTMO merely indexes the reports in [mozilla-reports](https://github.com/mozilla/mozilla-reports). It doesn't schedule or run those notebooks. To schedule or run notebooks you have to use ATMO or Airflow, so nothing has changed in that regard.

**Comment by RobertTStrong** [comment]
Closing pull request so this can instead live in https://github.com/mozilla/mozilla-reports

**Pull request closed without merging**
