### PR TITLE
Bug 1321414 - Create v2 desktop churn/retention dataset in telemetry-parquet

### PR DESCRIPTION
**Pull request by acmiyaguchi**
This code refactors the code for recurrent jobs on airflow. Involved with this patch are the following:

* Update dataframe.map to use dataframe.rdd.map (Spark 2.0)
* Remove loop computing backfill
* Join of newest_per_client and grouped_usage_time is flattened
* Miscellaneous formatting
* Get date from the environment
* Manual backfill logic implemented
* Output location changed from mreid/churn to amiyaguchi/churn

This will eventually get saved to `telemetry-parquet/churn/v2`, partitioned by week start. I'm in the process of creating a backfill of a few months in `s3://net-mozaws-prod-us-west-2-pipeline-analysis/amiyaguchi/churn/v1` that I can use as a staging area to test it.

This also has the ability to save to csv, but it has been commented out in this particular commit. I'm wondering if the paths for those should stay the same. I also need to verify that they are the same file (diffs of the backfilled jobs should contain the same data).

r? @Dexterp37 @mreid-moz

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla-services/data-pipeline/236)

### CODE REVIEW

**Comment by Dexterp37** [comment]
I've taken a first pass here, it looks good overall. I left a few notes below. Did you test the output of the notebook against the output of the previous version?

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[reports/churn/Churn.ipynb, line 487 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/236#-KZ68Z85OTEW7DMRslwH:-KZ68Z86KztnhpcC4sWD:bh7moor) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/b565f79ef80873fa11971b253b72436cbd31fd00/reports/churn/Churn.ipynb#L487)):*
> ```
>     "\n",
>     "\n",
>     "def upload_to_s3(records, churn_outfile):\n",
> ```

Is this part still needed? Do we  intend on keeping both the CSV and the parquet output?

---

*[reports/churn/Churn.ipynb, line 604 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/236#-KZ69CLja5r1w17aPKn_:-KZ69CLja5r1w17aPKna:boozvqu) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/b565f79ef80873fa11971b253b72436cbd31fd00/reports/churn/Churn.ipynb#L604)):*
> ```
>     "\n",
>     "    churn_outfile = get_churn_filename(week_start, week_end)\n",
>     "    # upload_to_s3(records_df.rdd.collect(), churn_outfile)\n",
> ```

Please remove this line, uncomment it or add a comment explaining why it's disabled.

---

*[reports/churn/Churn.ipynb, line 622 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/236#-KZ6CavBAw65EcOxN9a4:-KZ6CavCPQUoUGfHeLPc:b-9mfgec) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/b565f79ef80873fa11971b253b72436cbd31fd00/reports/churn/Churn.ipynb#L622)):*
> ```
>     "\n",
>     "\n",
>     "def backfill(df, start_date_yyyymmdd):\n",
> ```

Since this isn't used anywhere in the notebook, could you please add a comment stating that it's available for use when doing manual backfill? Or  you can add a cell with a commented block of code at the bottom, as you did for the manual arbitrary week.

---

*[reports/churn/Churn.ipynb, line 624 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/236#-KZ674ZDd5pib5yg6CHh:-KZ674ZDd5pib5yg6CHi:b5umqax) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/b565f79ef80873fa11971b253b72436cbd31fd00/reports/churn/Churn.ipynb#L624)):*
> ```
>     "def backfill(df, start_date_yyyymmdd):\n",
>     "    \"\"\" Import data from a start date to an end date\"\"\"\n",
>     "    start_date = most_recent_sunday(_datetime.strptime(start_date_yyyymmdd, \"%Y%m%d\"))\n",
> ```

I think we can get rid of the |most_recent_sunday| function here and use the one provided by moztelemetry.standards, |snap_to_beginning_of_week|. This would become:

snap_to_beginning_of_week((_datetime.strptime(start_date_yyyymmdd, "%Y%m%d")), "Sunday")

---

*[reports/churn/Churn.ipynb, line 648 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/236#-KZ673OGPZjwaXGVv6H6:-KZ673OHKOkCX_11ut7E:b-9gl5ls) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/b565f79ef80873fa11971b253b72436cbd31fd00/reports/churn/Churn.ipynb#L648)):*
> ```
>     "\n",
>     "# 10 days of slack for incoming data + the 7 days used in churn computation\n",
>     "week_start_date = most_recent_sunday(_datetime.strptime(env_date, \"%Y%m%d\") - timedelta(17))\n",
> ```

You can use |snap_to_beginning_of_week| here as well.

---

*[reports/churn/Churn.ipynb, line 649 at r1](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/236#-KZ69l0sETtk6iwYLuY6:-KZ69l0sETtk6iwYLuY7:b83s7y0) ([raw file](https://github.com/mozilla-services/data-pipeline/blob/b565f79ef80873fa11971b253b72436cbd31fd00/reports/churn/Churn.ipynb#L649)):*
> ```
>     "# 10 days of slack for incoming data + the 7 days used in churn computation\n",
>     "week_start_date = most_recent_sunday(_datetime.strptime(env_date, \"%Y%m%d\") - timedelta(17))\n",
>     "compute_churn_week(dataset, fmt(week_start_date))"
> ```

How does this behave when date is from an old week? Does it really compute the data for the day we're interested in?

Moreover, AFAICT the slack dance is already taken care of by |compute_churn_week|. Is there any other reason to do it here as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/236#-:-KZ6Fo9ilFKC41y2z3Jh:bh892gt)*

**Comment by vitillo** [comment]
FYI, one of the reasons why we have rtmo is that it's way easier to review notebooks there since they get converted to markdown.

What's the benefit of having this notebook in this repository compared to having it in mozilla-reports?

**Comment by Dexterp37** [comment]
I think we should transition *all* of the reports in this repository to mozilla-reports, unless there's a compelling reason not to. @mreid-moz might have a strong opinion on this particular case, though.

I understand this is not strictly a report but, until it lives in this notebook form, I'd rather have it somewhere that's easier to review.

**Comment by acmiyaguchi** [comment]
I'll manage the rest of the updates to this bug in `mozilla/reports`. I can see the value in having reviews being done in markdown instead of raw json. I'll leave this open until the changes get merged in reports.

**Comment by mreid-moz** [comment]
I don't have a strong opinion about the location - as long as the raw `.ipynb` is available for running as a scheduled job, I'm satisfied.

That being said, we should delete the notebook from this repo (and the `churn-analysis` repo) once it has been added to moz-reports, and consider adding a readme.txt file at the old location(s) pointing to the new location.

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla-services/data-pipeline/236#-:-KZRWlxCHsVFRqmtxhnD:bkrlo19)*

**Comment by acmiyaguchi** [comment]
This pr has landed in mozilla-reports.

**Pull request closed without merging**
